name: macOS Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-11, macos-12]

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/build'
        build-type: 'Debug'
        build-vstgui-standalone: ON

    - uses: ./.github/actions/cmake
      with:
        source-dir: '${{github.workspace}}'
        build-dir: '${{github.workspace}}/build-non-deprecated'
        build-type: 'Debug'
        build-vstgui-standalone: ON
        enable-deprecated-methods: OFF
